version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=car_store_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d car_store_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
